// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2S27J_hcqfbHHd0hhXTWPG2V8cgrcecE',
    appId: '1:540468441816:web:99b1a0adbdd5850046ddad',
    messagingSenderId: '540468441816',
    projectId: 'bengkel-project-d3bac',
    authDomain: 'bengkel-project-d3bac.firebaseapp.com',
    storageBucket: 'bengkel-project-d3bac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ7aRECHBY2AE0QhlmUA7UYYD9Gm9ARK8',
    appId: '1:540468441816:android:551773c65575806e46ddad',
    messagingSenderId: '540468441816',
    projectId: 'bengkel-project-d3bac',
    storageBucket: 'bengkel-project-d3bac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU3yvsFRXLaiCsM3sEIUWZMeVyDSvyrGI',
    appId: '1:540468441816:ios:9c9f5d4ce40b8bc746ddad',
    messagingSenderId: '540468441816',
    projectId: 'bengkel-project-d3bac',
    storageBucket: 'bengkel-project-d3bac.firebasestorage.app',
    iosBundleId: 'com.example.webBengkelMitsubishi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU3yvsFRXLaiCsM3sEIUWZMeVyDSvyrGI',
    appId: '1:540468441816:ios:9c9f5d4ce40b8bc746ddad',
    messagingSenderId: '540468441816',
    projectId: 'bengkel-project-d3bac',
    storageBucket: 'bengkel-project-d3bac.firebasestorage.app',
    iosBundleId: 'com.example.webBengkelMitsubishi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2S27J_hcqfbHHd0hhXTWPG2V8cgrcecE',
    appId: '1:540468441816:web:d9002c628168e42446ddad',
    messagingSenderId: '540468441816',
    projectId: 'bengkel-project-d3bac',
    authDomain: 'bengkel-project-d3bac.firebaseapp.com',
    storageBucket: 'bengkel-project-d3bac.firebasestorage.app',
  );
}
